@url = http://localhost:5128/api/v1/habits


### Create Habit
POST {{url}}
Content-Type: application/json
Accept: application/json

{
  "name": "Morning Jog",
  "description": "Jog for at least 30 minutes",
  "frequency": "Daily",
  "iconName": "run",
  "color": "#FF5733",
  "priority": 1,
  "difficultyLevel": 3,
  "startDate": "2025-07-01T06:30:00Z",
  "endDate": "2025-12-31T06:30:00Z",
  "preferredTime": "06:30:00",
  "isPublic": true,
  "notificationsEnabled": true,
  "reminderMinutesBefore": 15,
  "sortOrder": 0,
  "notes": "Avoid rainy days",
  "createdAt": "2025-07-01T00:00:00Z",
  "archivedAt": null,
  "categoryId": 5
}
### Get Habit
GET {{url}}/1
Accept: application/json