@url = http://localhost:5128/api/v1/habits

### Create Habit
POST {{url}}
Content-Type: application/json
Accept: application/json

{
  "id": 0, 
  "name": "Morning Jog",
  "description": "Jog for at least 30 minutes",
  "userId": "74ea04cf-51c1-475a-bafc-d6c7c252ca2b",
  "frequency": 0,
  "iconName": "run",
  "color": "#FF5733",
  "priority": 1,
  "difficultyLevel": 3,
  "startDate": "2025-07-01T06:30:00Z",
  "endDate": "2025-07-31T06:30:00Z",
  "preferredTime": "06:30:00",
  "isPublic": true,
  "notificationsEnabled": true,
  "reminderMinutesBefore": 15,
  "sortOrder": 0,
  "notes": "Avoid rainy days",
  "createdAt": "2025-07-01T00:00:00Z",
  "archivedAt": null,
  "categoryId": 5
}
### Get Habit
GET {{url}}/1
Accept: application/json

### Update Habit
PUT {{url}}/30013
Content-Type: application/json
Accept: application/json

{
  "id": 30013,
  "name": "Test2 Updated22",
  "description": "Test Updated Description",
  "userId": "74ea04cf-51c1-475a-bafc-d6c7c252ca2b",
  "frequency": 0,
  "iconName": "star-outline",
  "color": "#4ECDC4",
  "priority": 2,
  "difficultyLevel": 3,
  "startDate": "2025-07-18T13:20:31.532Z",
  "endDate": null,
  "preferredTime": null,
  "isPublic": false,
  "notificationsEnabled": false,
  "reminderMinutesBefore": 0,
  "sortOrder": 0,
  "notes": "",
  "createdAt": "2025-07-19T01:22:36.659",
  "archivedAt": null,
  "categoryId": 1
}

### Delete Habit
DELETE {{url}}/1?userId=74ea04cf-51c1-475a-bafc-d6c7c252ca2b
Accept: application/json