@url = http://localhost:5128/habits

### Get Habits
GET {{url}}/8c205c51-704b-4eec-8792-34e285c71a47
Accept: application/json


### Create Habit
POST {{url}}
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "name": "Daily Reading",
  "description": "Read at least 20 pages every day",
  "frequency": 0,
  "createdAt": "2024-06-01T10:00:00Z",
  "archivedAt": null,
  "userId": "8c205c51-704b-4eec-8792-34e285c71a47",
  "user": null,
  "categoryId": null,
  "category": null,
  "habitEntries": [
  ]
}