@url = http://localhost:5128/api/v1/users

### Get User
GET {{url}}/8c205c51-704b-4eec-8792-34e285c71a47
Accept: application/json

### Get User By Email
GET {{url}}?email=eden@gmail.com
Accept: application/json

### Create User

POST {{url}}
Content-Type: application/json
Accept: application/json

{
  "email": "eden@gmail.com",
  "password": "Password01!",
  "firstName": "Eden",
  "lastName": "Park",
  "dateOfBirth": "2025-04-21T07:31:51.952Z"
}

### Patch User

PATCH {{url}}/8c205c51-704b-4eec-8792-34e285c71a47
Content-Type: application/json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/firstName",
    "value": "UpdatedFirstName"
  },
  {
    "op": "replace",
    "path": "/lastName",
    "value": "UpdatedLastName"
  }
]


### Get Habits
GET {{url}}/8c205c51-704b-4eec-8792-34e285c71a47/habits
Accept: application/json