@url = http://localhost:5128/api/v1/users
@userId = 74ea04cf-51c1-475a-bafc-d6c7c252ca2b
### Get User
GET {{url}}/{{userId}}
Accept: application/json

### Get User By Email
GET {{url}}?email=eden@gmail.com
Accept: application/json

### Create User

POST {{url}}
Content-Type: application/json
Accept: application/json

{
  "email": "eden@gmail.com",
  "password": "Password01!",
  "firstName": "Eden",
  "lastName": "Park",
  "dateOfBirth": "2025-04-21T07:31:51.952Z"
}

### Patch User

PATCH {{url}}/{{userId}}
Content-Type: application/json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/firstName",
    "value": "UpdatedFirstName"
  },
  {
    "op": "replace",
    "path": "/lastName",
    "value": "UpdatedLastName"
  }
]


### Get Habits
GET {{url}}/{{userId}}/habits?date=2025-07-07
Accept: application/json